title: Stackbit Ampersand Theme
baseURL: /
params:
  layout_style: grid
  palette: green
  header:
    title: Rural Living in New Hampshire
    logo_img: images/rural-new-hampshire-living.png
    has_nav: true
  footer:
    content: '&copy; All rights reserved.'
    links:
      - text: Made with Stackbit
        url: 'https://www.stackbit.com'
        new_window: true
    has_social: true
disableKinds:
  - RSS
